### ISSUE TITLE
Problem setting up the keyring api.

### ISSUE THREAD

**Issue by dhananjaybhandiwad** [Fraunhofer-AISEC/ids-clearing-house-core#7]
I followed the detailed documentation for setting up the service. I have attached all the important files required to run the keyring api service. Please let me know if I have done something wrong while setting up the docker-compose.yml file.

1)This is the compose file I created.
![compose](https://user-images.githubusercontent.com/91888251/161014629-d5beb79e-c628-434f-b9fb-6a6753dda86d.png)
2)This is the Rocket file.
![Rocket](https://user-images.githubusercontent.com/91888251/161014716-2f713b82-4c51-4f0c-9f48-0c678466c827.png)

If the above configuration is wrong please let me know.

I get the following error when I run the compose file of keyring.
![keyring_error](https://user-images.githubusercontent.com/91888251/161016115-31217528-eff8-4245-a929-9a57dd7d9f79.png)

I have tried many things but they didn't work. It would be very grateful if I could get some help or direction

**Comment by kragall** [comment]
You configured two services in your `docker-compose.yml`: `keyring-api` and `keyring-mongo`. That means your database is running in the `keyring-mongo` container, but since you enabled port mapping you can access the database also from your host.

Now, in the `Rocket.toml` you configured the `keyring-api` to look for the database on `0.0.0.0` in the `keyring-api` container. You will need to either use the IP of your host or the address of the `keyring-mongo` container. For the latter you could simply have used the [Rocket.toml](https://github.com/Fraunhofer-AISEC/ids-clearing-house-core/blob/master/keyring-api/Rocket.toml) file as it is available in the repo.

**Comment by dhananjaybhandiwad** [comment]
Hey @kragall I tried exactly what you suggested. I get the following error.
![key-ring](https://user-images.githubusercontent.com/91888251/161512856-85c76d2b-c823-4a7f-a48f-7013f679f6a1.png)


I kept the Rocket file as it is like you suggested above, Just changed the port number where I mapped mongo.

**Comment by kragall** [comment]
The log clearly states `MissingField("database_url")` and the file I linked to contains the field, which tells me that you didn't use that file. Please read the [documentation](https://github.com/Fraunhofer-AISEC/ids-clearing-house-core#keyring-api) and make sure that you use configuration files that contain the required fields

**Comment by dhananjaybhandiwad** [comment]
this solution https://github.com/Fraunhofer-AISEC/ids-clearing-house-core/issues/3 works.
